from flask import Blueprint, request, jsonify, session, send_file
from flask_login import current_user, login_required
from app.services.assessment_service import process_assessment
from app.models.result import Result
from app.core.questions import QUESTIONS
import io
from fpdf import FPDF

assessment_bp = Blueprint('assessment', __name__)

@assessment_bp.route('/api/download-report', methods=['GET'])
@login_required
def download_report():
    # Get the latest result for the user
    result = Result.query.filter_by(user_id=current_user.id).order_by(Result.id.desc()).first()
    
    if not result:
        return jsonify({"error": "No assessment result found. Please complete an assessment first."}), 404
        
    # Generate PDF
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(45, 75, 143) # #2d4b8f
    pdf.cell(0, 20, "JobReady Career Report", 0, 1, 'C')
    pdf.ln(10)
    
    # User Info
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(51, 51, 51)
    pdf.cell(0, 10, f"Name: {current_user.name}", 0, 1)
    pdf.cell(0, 10, f"Email: {current_user.email}", 0, 1)
    pdf.ln(5)
    
    # Career Recommendation
    pdf.set_draw_color(221, 221, 221)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 10, "Recommended Career Path", 0, 1)
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(61, 180, 255) # #3db4ff
    pdf.cell(0, 15, result.career, 0, 1)
    pdf.ln(5)
    
    # Readiness Score
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(51, 51, 51)
    pdf.cell(0, 10, f"Overall Readiness Score: {result.score}%", 0, 1)
    pdf.ln(10)
    
    # Skill Breakdown
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 10, "Skill Breakdown", 0, 1)
    pdf.ln(5)
    
    pdf.set_font("Arial", '', 14)
    for skill, value in result.skills.items():
        if skill == "Readiness": continue
        pdf.cell(100, 10, f"{skill}:", 0, 0)
        pdf.cell(0, 10, f"{value}%", 0, 1)
        
    pdf.ln(10)
    
    # Skill Gaps
    if result.gaps:
        pdf.set_font("Arial", 'B', 18)
        pdf.cell(0, 10, "Skill Gaps & Areas for Improvement", 0, 1)
        pdf.ln(5)
        pdf.set_font("Arial", '', 12)
        for gap in result.gaps:
            pdf.multi_cell(0, 10, f"• {gap}", 0, 1)
            
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(136, 136, 136)
    pdf.cell(0, 10, "Generated by JobReady AI Career Assessment Platform", 0, 1, 'C')
    
    # Output PDF to memory
    output = io.BytesIO()
    pdf_content = pdf.output(dest='S')
    output.write(pdf_content)
    output.seek(0)
    
    return send_file(
        output,
        mimetype='application/pdf',
        as_attachment=True,
        download_name=f"JobReady_Report_{current_user.name.replace(' ', '_')}.pdf"
    )

@assessment_bp.route('/api/current-question', methods=['GET'])
@login_required
def get_current_question():
    current_index = session.get('current_question_index', 0)
    
    if current_index >= len(QUESTIONS):
        return jsonify({"finished": True})
        
    return jsonify({
        "question": QUESTIONS[current_index],
        "current": current_index + 1,
        "total": len(QUESTIONS)
    })

@assessment_bp.route('/api/next-question', methods=['POST'])
@login_required
def next_question():
    data = request.json
    answer = data.get('answer')
    
    if 'answers' not in session:
        session['answers'] = []
    
    current_index = session.get('current_question_index', 0)
    
    # Store or update the answer
    answers = list(session['answers']) # Ensure it's a list
    if current_index < len(answers):
        answers[current_index] = answer
    else:
        # Pad with None if somehow the index jumped
        while len(answers) < current_index:
            answers.append(None)
        answers.append(answer)
    session['answers'] = answers
    
    # Increment index
    session['current_question_index'] = current_index + 1
    
    finished = session['current_question_index'] >= len(QUESTIONS)
    
    # Proactively process assessment if finished to avoid race conditions
    if finished:
        answers_dict = {str(i): ans for i, ans in enumerate(answers)}
        process_assessment(current_user.id, answers_dict)
        # Clear session after submission
        session.pop('current_question_index', None)
        session.pop('answers', None)
    
    return jsonify({
        "success": True,
        "finished": finished
    })

@assessment_bp.route('/api/previous-question', methods=['POST'])
@login_required
def previous_question():
    current_index = session.get('current_question_index', 0)
    
    if current_index > 0:
        session['current_question_index'] = current_index - 1
        return jsonify({"success": True})
    
    return jsonify({"error": "Already at the first question"}), 400

@assessment_bp.route('/api/submit', methods=['POST'])
@login_required
def submit():
    # This is now a backup or manual trigger, primary submission happens in next_question
    answers = session.get('answers', [])
    
    if not answers:
        # Check if we already have a result from the pro-active submission
        from app.models.result import Result
        result = Result.query.filter_by(user_id=current_user.id).order_by(Result.id.desc()).first()
        if result:
            return jsonify({
                "career": result.career,
                "score": result.score,
                "skills": result.skills,
                "gaps": result.gaps
            })
        return jsonify({"error": "No answers provided"}), 400

    # Convert session list to dict for processing
    answers_dict = {str(i): ans for i, ans in enumerate(answers)}
    
    result = process_assessment(current_user.id, answers_dict)
    
    # Clear session after submission
    session.pop('current_question_index', None)
    session.pop('answers', None)

    return jsonify({
        "career": result.career,
        "score": result.score,
        "skills": result.skills,
        "gaps": result.gaps
    })

@assessment_bp.route('/api/result', methods=['GET'])
@login_required
def get_result():
    # Get the latest result for the current user
    result = Result.query.filter_by(user_id=current_user.id).order_by(Result.id.desc()).first()
    
    if not result:
        return jsonify({"error": "No result found"}), 404
        
    return jsonify({
        "career": result.career,
        "score": result.score,
        "skills": result.skills,
        "gaps": result.gaps
    })